function Ahat=FnMixingCalc(w,k,c,n)
g=nchoosek(n-1,k-1);
Cx=nchoosek(1:c,g);
Cg=size(Cx,1);
% f=nchoosek(n,g);
% Cg=nchoosek(c,g);
for i=1:Cg
    wbar=w(:,Cx(i,:));
    R=wbar*wbar';
    [V,D]= eig(R);
    [Val,Ix] =sort(diag(D));
    MinEV(i)=abs(Val(1))/abs(Val(end));
    MinEV(i)=abs(Val(1));
    MinInd(i)=Ix(1);
    VV(:,i)=V(:,Ix(1));
end
[Val,Ix] =sort( MinEV);
f=n;
% temp=VV(:,Ix(1:Cg));
Ahat=VV(:,Ix(1:f));
